import { Injectable, Logger } from '@nestjs/common';
// eslint-disable-next-line @typescript-eslint/no-var-requires
const PDFDocument = require('pdfkit');
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  convertInchesToTwip,
} from 'docx';

export interface ExportOptions {
  title:     string;
  subtitle?: string;
  content:   string;
  author?:   string;
}

@Injectable()
export class ExportService {
  private readonly logger = new Logger(ExportService.name);

  // ─── PDF ──────────────────────────────────────────────────────────────────

  async generatePdf(options: ExportOptions): Promise<Buffer> {
    const { title, subtitle, content, author } = options;

    return new Promise((resolve, reject) => {
      const doc    = new PDFDocument({ margin: 72, size: 'A4', info: { Title: title, Author: author ?? 'JobIN' } });
      const chunks: Buffer[] = [];

      doc.on('data',  (c: Buffer) => chunks.push(c));
      doc.on('end',   () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // ─ Header ───────────────────────────────────────────────────────────
      doc
        .fillColor('#1e40af')
        .font('Helvetica-Bold')
        .fontSize(22)
        .text(title, { align: 'center' });

      if (subtitle) {
        doc
          .fillColor('#6b7280')
          .font('Helvetica')
          .fontSize(11)
          .text(subtitle, { align: 'center' });
      }

      // Thin separator line
      doc.moveDown(0.5);
      doc
        .moveTo(72, doc.y)
        .lineTo(doc.page.width - 72, doc.y)
        .strokeColor('#e5e7eb')
        .lineWidth(0.5)
        .stroke();
      doc.moveDown(0.8);

      // ─ Body ─────────────────────────────────────────────────────────────
      const lines = content.split('\n');
      for (const line of lines) {
        const trimmed = line.trim();

        if (!trimmed) {
          doc.moveDown(0.4);
          continue;
        }

        // Detect common section headers (ALL CAPS, or ends with colon)
        const isHeader =
          (trimmed === trimmed.toUpperCase() && trimmed.length > 2 && trimmed.length < 60) ||
          (trimmed.endsWith(':') && trimmed.length < 50);

        if (isHeader) {
          doc.moveDown(0.5);
          doc
            .fillColor('#111827')
            .font('Helvetica-Bold')
            .fontSize(12)
            .text(trimmed, { align: 'left' });
          // Underline
          const tw = doc.widthOfString(trimmed);
          doc
            .moveTo(72, doc.y + 1)
            .lineTo(72 + tw, doc.y + 1)
            .strokeColor('#93c5fd')
            .lineWidth(1)
            .stroke();
          doc.moveDown(0.3);
        } else if (trimmed.startsWith('•') || trimmed.startsWith('-') || trimmed.startsWith('*')) {
          doc
            .fillColor('#374151')
            .font('Helvetica')
            .fontSize(10)
            .text(trimmed, { indent: 14, lineGap: 2 });
        } else {
          doc
            .fillColor('#374151')
            .font('Helvetica')
            .fontSize(10)
            .text(trimmed, { lineGap: 2 });
        }
      }

      // ─ Footer ───────────────────────────────────────────────────────────
      const pageHeight = doc.page.height;
      doc
        .fillColor('#9ca3af')
        .font('Helvetica')
        .fontSize(8)
        .text(
          `Generated by JobIN · ${new Date().toLocaleDateString('en-GB', { dateStyle: 'long' })}`,
          72,
          pageHeight - 48,
          { align: 'center', width: doc.page.width - 144 },
        );

      doc.end();
    });
  }

  // ─── DOCX ─────────────────────────────────────────────────────────────────

  async generateDocx(options: ExportOptions): Promise<Buffer> {
    const { title, subtitle, content } = options;

    const children: Paragraph[] = [
      // Title
      new Paragraph({
        children: [
          new TextRun({ text: title, bold: true, size: 36, color: '1e40af' }),
        ],
        alignment: AlignmentType.CENTER,
        spacing:   { after: 120 },
      }),
    ];

    // Subtitle
    if (subtitle) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: subtitle, size: 20, color: '6b7280' })],
          alignment: AlignmentType.CENTER,
          spacing:   { after: 240 },
          border:    {
            bottom: { style: BorderStyle.SINGLE, size: 2, color: 'e5e7eb' },
          },
        }),
      );
    }

    // Body lines
    const lines = content.split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) {
        children.push(new Paragraph({ spacing: { before: 60, after: 60 } }));
        continue;
      }

      const isHeader =
        (trimmed === trimmed.toUpperCase() && trimmed.length > 2 && trimmed.length < 60) ||
        (trimmed.endsWith(':') && trimmed.length < 50);

      const isBullet = trimmed.startsWith('•') || trimmed.startsWith('-') || trimmed.startsWith('*');

      if (isHeader) {
        children.push(
          new Paragraph({
            heading:  HeadingLevel.HEADING_2,
            children: [new TextRun({ text: trimmed, bold: true, size: 24, color: '111827' })],
            spacing:  { before: 240, after: 80 },
            border:   { bottom: { style: BorderStyle.SINGLE, size: 2, color: '93c5fd' } },
          }),
        );
      } else if (isBullet) {
        children.push(
          new Paragraph({
            bullet:   { level: 0 },
            children: [new TextRun({ text: trimmed.replace(/^[•\-*]\s*/, ''), size: 20, color: '374151' })],
            spacing:  { after: 40 },
            indent:   { left: convertInchesToTwip(0.25) },
          }),
        );
      } else {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: trimmed, size: 20, color: '374151' })],
            spacing:  { after: 60 },
          }),
        );
      }
    }

    // Footer paragraph
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text:  `Generated by JobIN · ${new Date().toLocaleDateString('en-GB', { dateStyle: 'long' })}`,
            size:  16,
            color: '9ca3af',
          }),
        ],
        alignment: AlignmentType.CENTER,
        spacing:   { before: 480 },
      }),
    );

    const doc = new Document({
      creator: 'JobIN',
      title,
      description: 'Generated by JobIN AI',
      sections: [{
        properties: {
          page: {
            margin: {
              top:    convertInchesToTwip(1),
              bottom: convertInchesToTwip(1),
              left:   convertInchesToTwip(1),
              right:  convertInchesToTwip(1),
            },
          },
        },
        children,
      }],
    });

    return Packer.toBuffer(doc);
  }

  /** Sanitise a string to be safe as a filename */
  toFilename(base: string, ext: 'pdf' | 'docx'): string {
    return `${base.replace(/[^a-zA-Z0-9\s-]/g, '').trim().replace(/\s+/g, '_').slice(0, 80)}.${ext}`;
  }
}
