import { Test, TestingModule } from '@nestjs/testing';
import { JwtService } from '@nestjs/jwt';
import { ConfigService } from '@nestjs/config';
import { ConflictException, UnauthorizedException } from '@nestjs/common';
import { AuthService } from './auth.service';
import { PrismaService } from '../prisma/prisma.service';

const mockPrismaService = {
  user: {
    findUnique: jest.fn(),
    create: jest.fn(),
    update: jest.fn(),
  },
  aICredits: {
    findUnique: jest.fn(),
  },
};

const mockJwtService = {
  sign: jest.fn().mockReturnValue('mock-jwt-token'),
};

const mockConfigService = {
  get: jest.fn((key: string) => {
    const config: Record<string, any> = {
      'app.jwtSecret': 'test-secret',
      'app.jwtExpiresIn': '7d',
    };
    return config[key];
  }),
};

describe('AuthService', () => {
  let service: AuthService;

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [
        AuthService,
        { provide: PrismaService, useValue: mockPrismaService },
        { provide: JwtService, useValue: mockJwtService },
        { provide: ConfigService, useValue: mockConfigService },
      ],
    }).compile();

    service = module.get<AuthService>(AuthService);
    jest.clearAllMocks();
  });

  describe('register', () => {
    it('should register a new user and create AI credits with 50 remaining', async () => {
      const dto = {
        email: 'test@example.com',
        password: 'SecurePass123!',
        fullName: 'Test User',
      };

      mockPrismaService.user.findUnique.mockResolvedValue(null);
      mockPrismaService.user.create.mockResolvedValue({
        id: 'user-uuid-1',
        email: dto.email,
        fullName: dto.fullName,
        status: 'ACTIVE',
        createdAt: new Date(),
        aiCredits: { remaining: 50 },
      });

      const result = await service.register(dto);

      expect(mockPrismaService.user.findUnique).toHaveBeenCalledWith({
        where: { email: dto.email },
      });
      expect(mockPrismaService.user.create).toHaveBeenCalledWith(
        expect.objectContaining({
          data: expect.objectContaining({
            email: dto.email,
            fullName: dto.fullName,
            aiCredits: { create: { remaining: 50 } },
          }),
        }),
      );
      expect(result.accessToken).toBe('mock-jwt-token');
      expect(result.user.email).toBe(dto.email);
      expect(result.user.aiCredits).toBe(50);
    });

    it('should throw ConflictException if email already exists', async () => {
      mockPrismaService.user.findUnique.mockResolvedValue({
        id: 'existing-user',
        email: 'existing@example.com',
      });

      await expect(
        service.register({
          email: 'existing@example.com',
          password: 'SecurePass123!',
          fullName: 'Existing User',
        }),
      ).rejects.toThrow(ConflictException);
    });
  });

  describe('login', () => {
    it('should return access token and user info on valid credentials', async () => {
      // We need a valid hash to test - use a known hash
      const password = 'SecurePass123!';
      // Call the private hashPassword via the register flow first
      // Instead, we'll mock a user with a password hash that was generated by the service
      const crypto = require('crypto');
      const salt = 'abc123def456abc123def456abc123de';
      const hash = crypto.pbkdf2Sync(password, salt, 10000, 64, 'sha512').toString('hex');
      const passwordHash = `${salt}:${hash}`;

      const mockUser = {
        id: 'user-uuid-1',
        email: 'test@example.com',
        fullName: 'Test User',
        passwordHash,
        status: 'ACTIVE',
        roles: [{ role: { name: 'USER' } }],
        aiCredits: { remaining: 45 },
      };

      mockPrismaService.user.findUnique.mockResolvedValue(mockUser);
      mockPrismaService.user.update.mockResolvedValue({ ...mockUser });

      const result = await service.login({
        email: 'test@example.com',
        password,
      });

      expect(result.accessToken).toBe('mock-jwt-token');
      expect(result.user.email).toBe('test@example.com');
      expect(result.user.roles).toContain('USER');
    });

    it('should throw UnauthorizedException on invalid password', async () => {
      const mockUser = {
        id: 'user-uuid-1',
        email: 'test@example.com',
        passwordHash: 'invalidsalt:invalidhash',
        status: 'ACTIVE',
        roles: [],
        aiCredits: null,
      };

      mockPrismaService.user.findUnique.mockResolvedValue(mockUser);

      await expect(
        service.login({ email: 'test@example.com', password: 'wrongpassword' }),
      ).rejects.toThrow(UnauthorizedException);
    });

    it('should throw UnauthorizedException for suspended user', async () => {
      mockPrismaService.user.findUnique.mockResolvedValue({
        id: 'user-uuid-1',
        email: 'suspended@example.com',
        passwordHash: 'somesalt:somehash',
        status: 'SUSPENDED',
        roles: [],
        aiCredits: null,
      });

      await expect(
        service.login({ email: 'suspended@example.com', password: 'anypassword' }),
      ).rejects.toThrow(UnauthorizedException);
    });

    it('should throw UnauthorizedException when user not found', async () => {
      mockPrismaService.user.findUnique.mockResolvedValue(null);

      await expect(
        service.login({ email: 'notfound@example.com', password: 'password' }),
      ).rejects.toThrow(UnauthorizedException);
    });
  });
});
